#!/usr/bin/env python3
"""Plot scalar ridge lambda estimates over GD epochs from saved data."""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import torch
from cmap import Colormap


LOGGER = logging.getLogger(__name__)
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = REPO_ROOT / "data" / "generated" / "lambda_vs_epochs" / "results.pt"
DEFAULT_OUTPUT = REPO_ROOT / "results" / "figures" / "lambda_vs_epochs.pdf"
STYLE_PATH = REPO_ROOT / "clean_fig.mplstyle"
REQUIRED_KEYS = {
    "epoch_grid",
    "iter_lambdas",
    "closed_lambdas",
    "theoretical_lambdas",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="Input .pt data generated by analysis/lambda_vs_epochs/run.py.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Canonical output path for the manuscript figure.",
    )
    return parser.parse_args()


def configure_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    logging.getLogger("fontTools").setLevel(logging.WARNING)


def configure_plot_style() -> None:
    if STYLE_PATH.exists():
        plt.style.use(str(STYLE_PATH))


def load_payload(path: Path) -> dict[str, Any]:
    payload = torch.load(path, weights_only=False)
    missing = REQUIRED_KEYS.difference(payload)
    if missing:
        raise KeyError(f"{path} is missing required keys: {sorted(missing)}")
    return payload


def plot_lambda_vs_epochs(payload: dict[str, Any], out_path: Path) -> None:
    configure_plot_style()
    fig, ax = plt.subplots(figsize=(5.0, 3.4))

    batlow = Colormap("crameri:batlow").to_mpl()
    c_iter, c_closed, c_theory = batlow(0.2), batlow(0.55), batlow(0.85)

    ax.loglog(
        payload["epoch_grid"],
        payload["iter_lambdas"],
        "o-",
        color=c_iter,
        label=r"Iterative $\hat{\lambda}_t$ (gradient matching)",
        markersize=6,
    )
    ax.loglog(
        payload["epoch_grid"],
        payload["closed_lambdas"],
        "x",
        color=c_closed,
        label=r"Closed-form $\hat{\lambda}_t$",
        markersize=8,
        markeredgewidth=1.8,
    )
    ax.loglog(
        payload["epoch_grid"],
        payload["theoretical_lambdas"],
        "--",
        color=c_theory,
        label=r"Theoretical $\mathrm{tr}(Q_t)/p$",
        linewidth=1.5,
    )

    ax.set_xlabel("Gradient descent epochs $t$")
    ax.set_ylabel(r"Scalar ridge penalty $\hat{\lambda}_t$")
    ax.legend(frameon=False, loc="lower left", fontsize=10)
    ax.grid(True, which="both", alpha=0.3)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    plt.close(fig)
    LOGGER.info("Saved %s", out_path)


def main() -> None:
    configure_logging()
    args = parse_args()
    plot_lambda_vs_epochs(load_payload(args.input), args.out)


if __name__ == "__main__":
    main()
