[project]
name = "core"
version = "0.1.0"
description = ""
authors = [{ name = "CENSORED", email = "CENSORED" }]
requires-python = "~=3.12.0"
readme = "README.md"
dependencies = [
    "torch>=2.6.0,<3",
    "lightning==2.6.1",
    "wandb>=0.19.8,<0.26.2",
    "numpy>=2.2.3,<3",
    "seaborn>=0.13.2,<0.14",
    "ipykernel>=6.29.5,<7",
    "ipywidgets>=8.1.5,<9",
    "accelerate>=1.4.0,<2",
    "scipy>=1.15.2,<2",
    "transformers>=4.49.0,<5",
    "datasets>=3.3.2,<4",
    "torchviz>=0.0.3,<0.0.4",
    "scikit-learn>=1.6.1,<2",
    "pytest>=8.3.5,<9",
    "nbformat>=5.10.4,<6",
    "torchopt>=0.7.3,<0.8",
    "optree>=0.17.0,<0.18",
    "huggingface-hub[cli]>=0.35.3,<0.36",
    "ffmpeg>=1.4",
    "ipympl>=0.9.8",
    "torchvision>=0.24.0",
    "nvidia-ml-py>=13.580.82",
    "cmap>=0.7.2",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv]
package = true
environments = [
    "sys_platform == 'darwin'",
    "sys_platform == 'linux'",
]

[tool.uv.sources]
lightning = { git = "https://github.com/Lightning-AI/pytorch-lightning.git", tag = "2.6.1" }
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux'" }
]
torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux'" }
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "snakemake>=9.19,<10",
    "snakemake-executor-plugin-slurm>=1",
    "pandas>=2.2",
    "pyarrow>=16",
]
