#!/usr/bin/env python3
"""Produces Barrett-style Figure 2 plus lambda recovery.

Reads data generated by analysis/barrett_igr_figure2/run.py and writes a
three-panel figure:
  (a) R_IG vs estimated lambda
  (b) test accuracy vs estimated lambda
  (c) estimated lambda vs Barrett's analytic lambda = eta * p / 4
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
from cmap import Colormap


REPO_ROOT = Path(__file__).resolve().parents[2]
RESULTS_FIGURES_DIR = REPO_ROOT / "results" / "figures"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--results",
        type=Path,
        default=REPO_ROOT / "data" / "generated" / "barrett_igr_figure2" / "results.pt",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=RESULTS_FIGURES_DIR / "barrett_igr_figure2.pdf",
    )
    parser.add_argument(
        "--x-quantity",
        choices=("lambda_hat", "lambda_theoretical"),
        default="lambda_hat",
        help="Which lambda to put on the x-axis.",
    )
    return parser.parse_args()


def grouped_means(
    x: np.ndarray,
    y: np.ndarray,
    num_params: np.ndarray,
    etas: np.ndarray,
    param_value: int,
) -> tuple[np.ndarray, np.ndarray]:
    xs = []
    ys = []
    mask_param = num_params == param_value
    for eta in sorted(np.unique(etas[mask_param]).tolist()):
        mask = mask_param & (etas == eta)
        xs.append(float(np.mean(x[mask])))
        ys.append(float(np.mean(y[mask])))
    order = np.argsort(xs)
    return np.array(xs)[order], np.array(ys)[order]


def main() -> None:
    args = parse_args()
    plt.style.use(str(REPO_ROOT / "clean_fig.mplstyle"))

    payload = torch.load(args.results, weights_only=False)
    all_results = payload["results"]
    results = [
        r
        for r in all_results
        if r.get("included", True) and "lambda_hat" in r and "r_ig" in r
    ]
    if not results:
        raise SystemExit("No included fitted results in file.")

    xs = np.array([r[args.x_quantity] for r in results], dtype=float)
    lambda_hat = np.array([r["lambda_hat"] for r in results], dtype=float)
    lambda_theoretical = np.array([r["lambda_theoretical"] for r in results], dtype=float)
    r_ig = np.array([r["r_ig"] for r in results], dtype=float)
    test_acc = np.array([r["best_test_acc"] for r in results], dtype=float)
    num_params = np.array([r["num_params"] for r in results], dtype=int)
    etas = np.array([r["eta"] for r in results], dtype=float)
    residuals = np.array([r["residual_ratio"] for r in results], dtype=float)

    unique_params = sorted(np.unique(num_params).tolist())
    cmap = Colormap("crameri:batlow").to_mpl()
    param_to_color = {
        m: cmap(i / max(1, len(unique_params) - 1))
        for i, m in enumerate(unique_params)
    }

    fig, axes = plt.subplots(1, 3, figsize=(14.5, 4.3))

    # Panel (a): R_IG vs lambda
    for m in unique_params:
        mask = num_params == m
        xm, ym = grouped_means(xs, r_ig, num_params, etas, m)
        axes[0].scatter(
            xs[mask],
            r_ig[mask],
            color=param_to_color[m],
            s=20,
            alpha=0.45,
            linewidth=0,
        )
        axes[0].plot(
            xm,
            ym,
            marker="o",
            linestyle="--",
            color=param_to_color[m],
            label=f"{m}",
            markersize=6,
            alpha=0.85,
            linewidth=1.0,
        )
    axes[0].set_xscale("log")
    axes[0].set_yscale("log")
    xlabel = r"$\hat{\lambda}$" if args.x_quantity == "lambda_hat" else r"Theoretical $\lambda = \eta m/4$"
    axes[0].set_xlabel(xlabel)
    axes[0].set_ylabel(r"$R_{IG} = \frac{1}{p}\|\nabla E(\theta)\|^2$")
    # axes[0].set_title("(a) Regularization vs $\\hat{\\lambda}$")
    axes[0].legend(title="# params", loc="lower left", fontsize=8, frameon=False)
    axes[0].grid(True, which="both", alpha=0.25)

    # Panel (b): test accuracy vs lambda
    for m in unique_params:
        mask = num_params == m
        xm, ym = grouped_means(xs, test_acc * 100, num_params, etas, m)
        axes[1].scatter(
            xs[mask],
            test_acc[mask] * 100,
            color=param_to_color[m],
            s=20,
            alpha=0.45,
            linewidth=0,
        )
        axes[1].plot(
            xm,
            ym,
            marker="o",
            linestyle="--",
            color=param_to_color[m],
            label=f"{m}",
            markersize=6,
            alpha=0.85,
            linewidth=1.0,
        )
    axes[1].set_xscale("log")
    axes[1].set_xlabel(xlabel)
    axes[1].set_ylabel("Test Accuracy (%)")
    # axes[1].set_title("Test accuracy vs $\\hat{\\lambda}$")
    axes[1].legend(title="# params", loc="lower right", fontsize=8, frameon=False)
    axes[1].grid(True, which="both", alpha=0.25)

    # Panel (c): estimated lambda vs Barrett analytic lambda.
    finite = np.isfinite(lambda_theoretical) & np.isfinite(lambda_hat)
    lo = min(float(lambda_theoretical[finite].min()), float(lambda_hat[finite].min()))
    hi = max(float(lambda_theoretical[finite].max()), float(lambda_hat[finite].max()))
    diag = np.geomspace(max(lo * 0.8, 1e-12), hi * 1.2, 200)
    axes[2].plot(diag, diag, color="black", linestyle=":", linewidth=1.1, alpha=0.7)
    for m in unique_params:
        mask = num_params == m
        axes[2].scatter(
            lambda_theoretical[mask],
            lambda_hat[mask],
            color=param_to_color[m],
            s=26,
            alpha=0.75,
            label=f"{m}",
            linewidth=0,
        )
    axes[2].set_xscale("log")
    axes[2].set_yscale("log")
    axes[2].set_xlabel(r"Theoretical $\lambda = \eta p/4$")
    axes[2].set_ylabel(r"$\hat{\lambda}$")
    axes[2].grid(True, which="both", alpha=0.25)

    config = payload.get("config", {})
    # fig.suptitle(
    #     f"Barrett & Dherin (2022) Figure 2 reproduction · {activation} MLP · "
    #     f"MNIST (n_train={train_samples})",
    #     fontsize=12,
    # )
    fig.tight_layout(rect=[0, 0, 1, 0.95])

    args.out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.out, bbox_inches="tight", pad_inches=0.02)
    print(f"Saved {args.out}")
    excluded = len(all_results) - len(results)
    ratio = lambda_hat / lambda_theoretical
    print(
        f"Data: n_fitted={len(results)}, n_excluded={excluded}, "
        f"lambda_hat range=[{lambda_hat.min():.3g}, {lambda_hat.max():.3g}], "
        f"lambda_hat/theory range=[{ratio.min():.3g}, {ratio.max():.3g}], "
        f"R_IG range=[{r_ig.min():.3g}, {r_ig.max():.3g}], "
        f"test_acc range=[{test_acc.min():.3f}, {test_acc.max():.3f}], "
        f"median residual_ratio={np.median(residuals):.3f}"
    )


if __name__ == "__main__":
    main()
