#!/usr/bin/env python3
"""Plot OLS early-stopping component figures from saved experiment data."""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import torch
from cmap import Colormap


LOGGER = logging.getLogger(__name__)
REPO_ROOT = Path(__file__).resolve().parents[2]
RESULTS_FIGURES_DIR = REPO_ROOT / "results" / "figures"
DEFAULT_INPUT = REPO_ROOT / "data" / "generated" / "linear_regression_ols" / "results.pt"
DEFAULT_LAMBDA_OUT = RESULTS_FIGURES_DIR / "Lambda_comparison-ols.pdf"
DEFAULT_WEIGHTS_OUT = RESULTS_FIGURES_DIR / "predictive_weights_comparison_ols.pdf"
STYLE_PATH = REPO_ROOT / "clean_fig.mplstyle"
DIVERGING_CMAP = Colormap("crameri:vik").to_mpl()
REQUIRED_KEYS = {
    "Q",
    "q_hat_diag",
    "theta_real",
    "theta_hat",
    "theta_hat_prime",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="Input .pt data generated by analysis/linear_regression_ols/run.py.",
    )
    parser.add_argument(
        "--lambda-out",
        type=Path,
        default=DEFAULT_LAMBDA_OUT,
        help="Output path for the learned-vs-theoretical Lambda heatmap.",
    )
    parser.add_argument(
        "--weights-out",
        type=Path,
        default=DEFAULT_WEIGHTS_OUT,
        help="Output path for the predictive-weights comparison heatmap.",
    )
    return parser.parse_args()


def configure_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    logging.getLogger("fontTools").setLevel(logging.WARNING)


def configure_plot_style() -> None:
    if STYLE_PATH.exists():
        plt.style.use(str(STYLE_PATH))


def load_payload(path: Path) -> dict[str, Any]:
    payload = torch.load(path, weights_only=False)
    missing = REQUIRED_KEYS.difference(payload)
    if missing:
        raise KeyError(f"{path} is missing required keys: {sorted(missing)}")
    return payload


def save_lambda_comparison(q_matrix: torch.Tensor, q_hat: torch.Tensor, out_path: Path) -> None:
    q_cpu = q_matrix.detach().cpu()
    qhat_cpu = q_hat.detach().cpu()
    vmax = max(q_cpu.abs().max().item(), qhat_cpu.abs().max().item())
    vmin = -vmax

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    norm = plt.Normalize(vmin=vmin, vmax=vmax)
    sns.heatmap(
        qhat_cpu.numpy(),
        ax=axes[0],
        cmap=DIVERGING_CMAP,
        norm=norm,
        square=True,
        cbar=False,
        xticklabels=False,
        yticklabels=False,
    )
    axes[0].set_title(r"Estimated $\hat{\Lambda}$")
    axes[0].set_xlabel(r"$p$")
    axes[0].set_ylabel(r"$p$")

    sns.heatmap(
        q_cpu.numpy(),
        ax=axes[1],
        cmap=DIVERGING_CMAP,
        norm=norm,
        square=True,
        cbar=False,
        xticklabels=False,
        yticklabels=False,
    )
    axes[1].set_title(r"Theoretical $\Lambda$")
    axes[1].set_xlabel(r"$p$")
    axes[1].set_ylabel("")

    for ax in axes:
        ax.tick_params(
            axis="both",
            which="both",
            bottom=False,
            left=False,
            labelbottom=False,
            labelleft=False,
        )

    scalar_mappable = plt.cm.ScalarMappable(cmap=DIVERGING_CMAP, norm=norm)
    scalar_mappable.set_array([])
    fig.colorbar(scalar_mappable, ax=axes, location="right", pad=0.04)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)
    LOGGER.info("Saved %s", out_path)


def save_predictive_weights_comparison(
    *,
    theta_real: np.ndarray,
    theta_hat: np.ndarray,
    theta_hat_prime: np.ndarray,
    out_path: Path,
) -> None:
    vmax = max(
        np.abs(theta_real).max(),
        np.abs(theta_hat).max(),
        np.abs(theta_hat_prime).max(),
    )
    norm = plt.Normalize(vmin=-vmax, vmax=vmax)

    fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(2, 6))
    for ax, theta, title in zip(
        axes.flatten(),
        [theta_hat_prime, theta_hat, theta_real],
        [r"$\hat{\theta}_{\Lambda}$", r"$\hat{\theta}$", r"$\theta$"],
        strict=True,
    ):
        sns.heatmap(
            theta.reshape(-1, 1),
            cmap=DIVERGING_CMAP,
            norm=norm,
            square=True,
            cbar=False,
            yticklabels=False,
            xticklabels=False,
            ax=ax,
            linewidths=0.5,
            linecolor="k",
        )
        ax.set_title(title, fontsize=20)
    axes[0].set_ylabel(r"$p$", fontsize=16)

    scalar_mappable = plt.cm.ScalarMappable(cmap=DIVERGING_CMAP, norm=norm)
    scalar_mappable.set_array([])
    plt.colorbar(
        scalar_mappable,
        ax=list(axes),
        orientation="horizontal",
        fraction=0.02,
        pad=0.05,
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)
    LOGGER.info("Saved %s", out_path)


def plot_payload(payload: dict[str, Any], lambda_out: Path, weights_out: Path) -> None:
    configure_plot_style()
    save_lambda_comparison(payload["Q"], payload["q_hat_diag"], lambda_out)
    save_predictive_weights_comparison(
        theta_real=payload["theta_real"].detach().cpu().numpy(),
        theta_hat=payload["theta_hat"].detach().cpu().numpy(),
        theta_hat_prime=payload["theta_hat_prime"].detach().cpu().numpy(),
        out_path=weights_out,
    )


def main() -> None:
    configure_logging()
    args = parse_args()
    plot_payload(load_payload(args.input), args.lambda_out, args.weights_out)


if __name__ == "__main__":
    main()
